### PR TITLE
update README file

### PR DESCRIPTION
**Pull request by naomijustin**

### CODE REVIEW

**Comment by malcolm-kee** [comment]
Hi @naomijustin thanks for the detailed writeup, this would be helpful for us to onboard other contributors!

After reading what you've written, I realize we can categorize the steps as

1. steps that will be required for anyone *in future* that wants to contribute.
1. steps that we had taken to setup this repo.

Therefore, here is what I suggest:

1. For type 2, we can create a `guide` folder and include the content in a `how-we-setup-this-repo.md` file. This is an education reference instead of a step-by-step guide for future contributors. What you've written is good to go, just need to move to another file.
1. In a separate PR, the steps that are only applicable for future contributors are extracted into a `CONTRIBUTING.md`.

What do you think?

**Comment by naomijustin** [comment]
Hi @malcolm-kee,

Yep I think that sounds great - I agree that should help for different types of contributors.

One suggestion - possibly we can create a short guide in the root readme to explain where to find the guide folder/relevant info so that the files are easy to navigate for their user flow. What do you think?

**Comment by malcolm-kee** [comment]
Yeah that sounds great. You can also create a link in README to that file directly, as described here: https://github.blog/2013-01-31-relative-links-in-markup-files/

**Comment by naomijustin** [comment]
Oh yep perfect - sounds good, I'll start on those changes.

**Comment by naomijustin** [comment]
Closing as separate pull request covers changes

**Pull request closed without merging**
